name: Debug Secrets Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  debug-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Debug Secrets
        run: |
          echo "Unmasked VITE_SUPABASE_URL: $VITE_SUPABASE_URL"
          echo "Unmasked VITE_SUPABASE_ANON_KEY: $VITE_SUPABASE_ANON_KEY"
          echo "Unmasked VITE_AUTH_REDIRECT_URL: $VITE_AUTH_REDIRECT_URL"
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_AUTH_REDIRECT_URL: ${{ secrets.VITE_AUTH_REDIRECT_URL }}
